default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  # Database was not set as an environment variable so you could have multiple projects on the same server locally
  # No harm in hard coding the database name in each project for development purposes.
  database: <%= ENV["POSTGRES_DATABASE"] ? ENV["POSTGRES_DATABASE"] : 'grocery_app_development'  %>
  username: <%= ENV["POSTGRES_USER"] ? ENV["POSTGRES_USER"] : 'eric' %>
  password: <%= ENV["POSTGRES_PASS"] ? ENV["POSTGRES_PASS"] : '' %>
  host: <%= ENV["POSTGRES_HOSTNAME"] ? ENV["POSTGRES_HOSTNAME"] : '127.0.0.1' %>
  port: <%= ENV["POSTGRES_PORT"] ? ENV["POSTGRES_PORT"] : '5432' %>

staging:
  <<: *default
  # Database was not set as an environment variable so you could have multiple projects on the same server locally
  # No harm in hard coding the database name in each project for development purposes.
  database: <%= ENV["POSTGRES_DATABASE"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASS"] %>
  host: <%= ENV["POSTGRES_HOSTNAME"] %>
  port: <%= ENV["POSTGRES_PORT"] %>

# tests
test:
  adapter: sqlite3
  database: ":memory:"
  verbosity: quiet

production:
  <<: *default
  database: testapp_production
  # username: testapp
  # password: <%= ENV["POSTGRES_PASSWORD"] %>
  # host: <%= ENV["POSTGRES_HOST"] %>
  # port: <%= ENV["POSTGRES_PORT"] %>